#!/bin/bash

if ! ./vendor/bin/phpstan analyse; then
    exit 1
fi

if ! ./vendor/bin/phpmd src ansi phpmd.xml; then
    exit 2
fi

if ! ./vendor/bin/phpcs src phpcs.xml; then
    exit 3
fi

if ! ./vendor/bin/phpunit --stop-on-failure --stop-on-error; then
    exit 4
fi